### ISSUE TITLE
openai.error.AuthenticationError

### ISSUE THREAD

**Issue by anilgoyal-gep** [Azure-Samples/azure-search-openai-demo#108]
Hi,

I get the below authentication error when I hit the query:

"openai.error.AuthenticationError: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."

I have set up the right keys in the env file and still it fails. 

I see the app.py is able to fetch the token and the flask app is up but this error pops up when I query.

P.S. I have also hardcoded the creds in the create function inside the openai library source code for testing, but the error persists.

**Comment by nsbuttar** [comment]
having a similar issue

**Comment by anilgoyal-gep** [comment]
Setting "openai.api_key, openai.api_base, openai.api_type, openai.api_version" in chatreadretrieveread.py resolved the issue for me

**Comment by YasBars01** [comment]
> Setting "openai.api_key, openai.api_base, openai.api_type, openai.api_version" in chatreadretrieveread.py resolved the issue for me



Something like this worked for me

```
os.environ["OPENAI_API_BASE"] = os.environ["AZURE_OPENAI_ENDPOINT"]
os.environ["OPENAI_API_KEY"] = os.environ["AZURE_OPENAI_API_KEY"]
os.environ["OPENAI_API_VERSION"] = os.environ["AZURE_OPENAI_API_VERSION"]
os.environ["OPENAI_API_TYPE"] = "azure"
```

This is even if i had dotenv loaded:

```
from dotenv import load_dotenv
load_dotenv()
```

**Comment by sohamok** [comment]
@anilgoyal-gep getting the same error even after specifying openai key, base, version and type inside chatreadretrieval.py init method

Logs:
  File "C:\Users\Ebiw\generative-ai\app\backend\app.py", line 134, in chat
    r = impl.run(request.json["history"], request.json.get("overrides") or {})
  File "C:\Users\Ebiw\generative-ai\app\backend\approaches\chatreadretrieveread.py", line 87, in run
    chat_completion = openai.ChatCompletion.create(
  File "C:\Users\Ebiw\generative-ai\app\backend\backend_env\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\Ebiw\generative-ai\app\backend\backend_env\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\Ebiw\generative-ai\app\backend\backend_env\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\Ebiw\generative-ai\app\backend\backend_env\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Ebiw\generative-ai\app\backend\backend_env\lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.

**Comment by pamelafox** [comment]
Can you try enabling logging via putting logging.basicConfig(level=logging.DEBUG) in the app.py create_app function? Then you can see what URL the openai package tries to reach.

**Comment by Shekharsittle** [comment]
hi i am getting error of "openai.error.AuthenticationError: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource." while using azure open ai , anyone please help.
