### ISSUE TITLE
Upload larger files

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [Azure-Samples/azure-search-openai-demo#1170]
When I want to use my own document that are larger than expected, then I get the following error:

 File "C:\Workspace\engenious\azure-search-openai-demo\scripts\.venv\Lib\site-packages\azure\ai\formrecognizer\_generated\v2023_07_31\aio\operations\_document_models_operations.py", line 114, in _analyze_document_initial
    raise HttpResponseError(response=response)
azure.core.exceptions.HttpResponseError: (InvalidRequest) Invalid request.
Code: InvalidRequest
Message: Invalid request.
Inner error: {
    "code": "InvalidContentLength",
    "message": "The input image is too large. Refer to documentation for the maximum file size."
}

How or where can I increase the file size in the code?
Regards
Andreas

**Comment by mattgotteiner** [comment]
Hello @andreas-sommer-engenious ,

The maximum file size for document intelligence is documented here
https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/concept-layout?view=doc-intel-4.0.0#input-requirements

The file size for analyzing documents is 500 MB for paid (S0) tier and 4 MB for free (F0) tier.

If you want to use a file larger than these, consider using the local PDF parser instead of document intelligence by replacing `"--formrecognizerservice $env:AZURE_FORMRECOGNIZER_SERVICE` in `./scripts/prepdocs.ps1' with `--localpdfparser`. This disables use of document intelligence and replaces it with a locally run PDF parser.

I hope this helps.

**Comment by andreas-sommer-engenious** [comment]
Thanks for your answer. That solved my problems.
