### ISSUE TITLE
Authentication Question

### ISSUE THREAD

**Issue by miggytrinidad** [Azure-Samples/azure-search-openai-demo#1236]
I am trying to understand the authentication code. I am trying to find where the /.auth/me is but couldn't find it or I am looking at the wrong place.

**Comment by pamelafox** [comment]
That actually comes from App Service's built in authentication feature: https://learn.microsoft.com/en-us/azure/app-service/configure-authentication-user-identities#access-user-claims-using-the-api
We just make requests to it, we don't need to implement it ourselves.

**Comment by miggytrinidad** [comment]
Appreciate this! You're doing a great job with this repo!

**Comment by miggytrinidad** [comment]
@pamelafox, in my flask server I am getting /.auth/me 404 error. Any idea on this?

**Comment by pamelafox** [comment]
That's intentional- we first do a fetch to that URL to see if we're currently on App Service with authentication.

**Comment by miggytrinidad** [comment]
@pamelafox, thanks for quick response! This might be too much to ask, but here's the use case:

1. FE and BE will be running on different quart/flask servers.

Any idea if I can reuse the authentication code setup you have here? or any advice on what to use for azure ad authentication? 
- currently, the authentication requires SPA APP registration setup. If this will not be possible, any advice?

**Comment by pamelafox** [comment]
Are they going to be running off different domains? (via CORS?) That might affect whether it works or requires additional configuration.

I feel like it should work since @mattgotteiner set this up using two app registrations already, one for the frontend and one for the backend. Have you already read through his blog post and doc for the overview of the auth here?

https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/access-control-in-generative-ai-applications-with-azure/ba-p/3956408

https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/login_and_acl.md
