### ISSUE TITLE
Vulnerability with python-jose

### ISSUE THREAD

**Issue by TaylorNQT** [Azure-Samples/azure-search-openai-demo#1616]
There is currently an issue with the python-jose package as described [here](https://github.com/mpdavis/python-jose/issues/346).

Potential fix is to replace with PyJWT.

**Comment by pamelafox** [comment]
cc @mattgotteiner 

It looks like our usage should not be affected by the vulnerability, since we do specify an algorithm:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/3822c5294dbc25ad21a8c060fcae44997485304f/app/backend/core/authentication.py#L343

Let me know if you think otherwise.

We're also aware that python-jose is generally unmaintained, but last I checked, pyJWT was still missing a feature that we needed to be able to move over to it. Happy to be corrected if it's a suitable substitute now.

Thanks so much for filing.

**Comment by TaylorNQT** [comment]
That's OK, I just wanted to make you aware :)
