### ISSUE TITLE
Connect AI Search to AI Studio Hub

### ISSUE THREAD

**Issue by phoevos** [Azure-Samples/azure-search-openai-demo#1784]
I am creating a hub and a project on AI Studio and I'd like to add a connection to Azure AI Search.

I understand that key-based authentication was disabled for the Search service as a security optimisation. However, API key authentication is the only method exposed through the AI Studio UI when creating a connection. At the same time, I see that the free tier for Search does not support managed identity. What can I do about this?

I'm not limited by what's exposed through AI Studio since I'm using Bicep for the deployment anyway. I'm just using the UI for reference, given that it's hard to tell what's actually supported for each kind of service/connection.

**Comment by cforce** [comment]
AFAIK AI studio chat bot creation is sundowned. Better understand the code and stick with you keyboard but mouse. It’s because the whole setup is still evolving to fast, so simple solutions are still not there:/

**Comment by pamelafox** [comment]
It looks like you are trying to use the On Your Data feature. That is not used by this repo. The closest repo is https://github.com/microsoft/sample-app-aoai-chatGPT since that is the code behind the On Your Data deployable app. 

However, for issues specific with AI Search, they recommend filing a support ticket with the service. Do you see an option in the Portal to file a support ticket?

I am closing this issue, since it's not something resolvable in this codebase.
