### ISSUE TITLE
Quart vs FastAPI

### ISSUE THREAD

**Issue by MPercianteQ** [Azure-Samples/azure-search-openai-demo#1785]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
>

We want to implement future AI projects using OpenAI hosted in Azure, but we are unsure about using Quart or FastAPI for the Python webserver. We´ve set up a little investigation for both, and can´t find any significant feature or difference that tilts the scale towards one.

Could anyone help us with it?

Not only talking about features. Any cost (implementation and maintenance), performance or scalability (or other) comparison is very useful too.

Thanks

### OS and Version?
> Windows 11

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
The most important thing is that you are using an async framework, so either of them should be good choices. Here is my experience, as I've developed with both of them on Azure:

* If you already have Flask apps, it is much easier to turn them into Quart apps than FastAPI apps, given that Quart is actually based on Flask and tries to mimic the Flask interface when possible.
* Quart is easier to use if your app includes static files / HTML routes. It is possible to use FastAPI for a full webapp, but it is harder. That said, I've figured it out in https://github.com/Azure-Samples/rag-postgres-openai-python/ so you can look at that for inspiration.
* FastAPI has built-in API documentation. To do that with Quart, you need to use Quart-Schema. That isn't terribly hard, and I even have a branch that does that for this repo, but it's obviously more tightly integrated into FastAPI.
* There are more extensions for Quart, largely due to many extensions being forked from Flask extensions. There is less of an extension ecosystem for FastAPI, perhaps because there is not an established extension ecosystem. There are many tutorials/examples that show how to do things, however, given the popularity of FastAPI.
* In terms of performance, I haven't particularly seen a difference, but I haven't done an A/B test of Quart vs FastAPI (only Quart vs Flask). You'll want to use either gunicorn with the uvicorn worker, as we do in this repo, or use uvicorn directly, as is possible in the latest release of uvicorn. Then you can run load tests (like we do with locust in this repo) and confirm you're seeing the performance characteristics you desire.
* Quart is an open-source project that is part of the Pallets ecosystem, and primarily maintained by github.com/pgjones. FastAPI is an open-source project, primarily maintained by github.com/tiangolo, who recently received funding to work on monetization strategies. Both of them are regularly maintained at this point, but I am sharing those details in case it affects your choice.

**Comment by pamelafox** [comment]
This was a great Q, so I also wrote my response as a blog post:
https://blog.pamelafox.org/2024/07/should-you-use-quart-or-fastapi-for-ai.html
