### ISSUE TITLE
UI error TypeError: Cannot read properties of undefined (reading 'role'). How to fix the issue.

### ISSUE THREAD

**Issue by haldernayan** [Azure-Samples/azure-search-openai-demo#1819]
<!--

> Please provide us with the following information:
> getting UI error TypeError: Cannot read properties of undefined (reading 'role') . any help how to solve this.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
 macOS

### azd version?
> run `azd version` and copy paste here.
### Versions
1.9.5
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Please look at the tracebacks on your server to debug the error. We can't tell the issue based on the frontend error. See the guide here for debugging tips:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/appservice.md

Typically the errors are resolvable once you find the Python traceback. If you are unable to debug the Python traceback, please open a new issue.

**Comment by cforce** [comment]
The issue is that running ap locally will already offer  a prompt even if not logged (button login right top need to be pressed and sucessfully auth with valid token in header as result) in.
If you access the prompt before it will raise below error.

ERROR:root:Exception getting authorization information - "Authorization header is expected"
Traceback (most recent call last):
  File "/mnt/c/git/openai/mic-docbot/app/backend/core/authentication.py", line 217, in get_auth_claims_if_enabled
    auth_token = AuthenticationHelper.get_token_auth_header(headers)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/git/openai/mic-docbot/app/backend/core/authentication.py", line 139, in get_token_auth_header
    raise AuthError(error="Authorization header is expected", status_code=401)
core.authentication.AuthError: Authorization header is expected
[2024-08-02 08:03:07 +0200] [252442] [INFO] 127.0.0.1:37452 POST /chat/stream 1.1 403 213 20529

As use_authentication is true it will try to read the sec header, but there is none at this moment- last line expcetion in below ocee
''' 
async def get_auth_claims_if_enabled(self, headers: dict) -> dict[str, Any]:
        if not self.use_authentication:
            return {}
        try:
            # Read the authentication token from the authorization header and exchange it using the On Behalf Of Flow
            # The scope is set to the Microsoft Graph API, which may need to be called for more authorization information
            # https://learn.microsoft.com/entra/identity-platform/v2-oauth2-on-behalf-of-flow
            auth_token = AuthenticationHelper.get_token_auth_header(headers)#  <----- raised exception

''' 

The solution would be to not render any prompt until the login /redirect was successful)

@pamelafox

**Comment by cforce** [comment]
Pleas reopen
