### ISSUE TITLE
Search service region - selection in list doesn't work with service regions

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/azure-search-openai-demo#1939]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
1. Deploy with azd up selecting from regions provided. 
- Select an Azure location to use: 30. (Europe) Sweden Central (swedencentral)
- Enter a value for the 'documentIntelligenceResourceGroupLocation' infrastructure parameter:  1. (Europe) West Europe (westeurope)
- Enter a value for the 'openAiResourceGroupLocation' infrastructure parameter:  5. (Europe) Sweden Central (swedencentral)
### Any log messages given by the failure
>

### Expected/desired behavior
>I expect if I pick a region from the provided list, that it works for the service. 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful
<img width="743" alt="image" src="https://github.com/user-attachments/assets/6f8cc5bd-5576-4893-9231-8f84eb230ce5">

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
This is the same error as https://github.com/Azure-Samples/azure-search-openai-demo/issues/1575
and https://github.com/Azure-Samples/azure-search-openai-demo/issues/1341
I believe, so I'll close it in favor of one of those discussions. We haven't added another region since it complicates the deploy and is only an issue for a small number of regions, but I don't think I would object to another parameter if a PR is sent.
