### ISSUE TITLE
Question: How to create an AZDO pipeline to deploy the code on an existing environment

### ISSUE THREAD

**Issue by ij-23** [Azure-Samples/azure-search-openai-demo#2206]
> Please provide us with the following information:
> ---------------------------------------------------------------

Hey,

I have an existing environment and I want to deploy the code on it.
The resources are configured with Private Endpoint and the so the Webapp.
I want to create a pipeline to build the app, and deploy it as a zip without using Oryx build. 

My question is what are the steps that I need to take in this case?

Thank you!

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### azd version?
> run `azd version` and copy paste here.

### Versions
> 1.11.0

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
I've discussed being able to deploy without Oryx build with @vhvb1989 and @jongio in the past. I haven't yet done it successfully however. There are a few obstacles you'll need to tackle:

* The limitation of zip deploy is 2 GB. Last we checked, this repository (with all its packages) is less than 2 GB, but not significantly less.
* The azd CLI does not include the venv, by default. However I think you can now create a ".webappignore" file to override what gets excluded or included.
* You would need to set the env variables in appservice.bicep so that it not longer did the Oryx build. That should be doable.

There's already a pipeline for AZDO in this repo, so if you get it working from the command-line with "azd up", then I would think that the pipeline would work as well.

Victor and Jon, did I miss anything?

Also: if it's easier to deploy to Container Apps, you could wait for us to add private endpoint support for ACA. I believe that's now in public preview as of the Ignite conference last week, I'll ask the ACA team about adding it to the repo.

**Comment by pamelafox** [comment]
For this app's private endpoint configuration, the webapp is no longer public, so it must be accessed via a VPN.

**Comment by ij-23** [comment]
* The app that we are willing to create is going to be only for our internal users and public access in not required.
* What do you mean by "azd CLI does not include the venv"? If my pipeline yaml file will be like this for example:

1. Fetch the code
2. Create the virtual environment and fetch all the packages that related to thebackend and frontend apps.
3. Zipping everything.
4. Deploying it.

Will it work?

**Comment by ij-23** [comment]
@pamelafox 

I took the steps from the last comment (without using Oryx) and now I'm getting this message:
`ModuleNotFoundError: No module named 'opentelemetry.semconv.ai'`

When I looked at the **site-packages** directory I found the **opentelemetry_semantic_conventions_ai** folder.

What am I missing?
