### ISSUE TITLE
Loading azd .env file from current environment

### ISSUE THREAD

**Issue by en-coded** [Azure-Samples/azure-search-openai-demo#457]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Update .env file with new parameters

I have two instances for azure-search-openai-demo. I am using one as a development environment and the other as a production-demo environment for frontend-related changes.

I want to update the .env file in the development instance with the values (except BACKEDN_URI) from the production-demo instance.

I can deploy the development instance without any issues; however, azd up gets stuck at this step:
Executing postprovision hook => ./scripts/prepdocs.sh
Loading azd .env file from current environment

### Any log messages given by the failure
> Loading azd .env file from current environment

### Expected/desired behavior
> azd up should deploy as expected

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
macOS Ventura
### azd version?
> run `azd version` and copy paste here.
1.1.0
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by olsgaard** [comment]
How do you manage your two azure envirionments?

In your .azure folder you should see two subfolders. These are where the settings and config for your two environments should be saved. It should look something like this:

```shell
.azure
├── config.json
├── myProd
│   ├── .env
│   └── config.json
└── myDev
    ├── .env
    └── config.json
```

Inside `.azure/config.json` it should say which one is your default environment. When calling `azd up` the default environment is used. Let's say "myDev" is your default. In that case, in order to push production, you are supposed to call `azd up -e myProd`

If you look inside `scripts/prepdocs.sh` you'll see this line of code

```shell
while IFS='=' read -r key value; do
    value=$(echo "$value" | sed 's/^"//' | sed 's/"$//')
    export "$key=$value"
done <<EOF
$(azd env get-values)
EOF
```
This is what loads the values from your azure environment into shell, before executing prepdocs.py, which in turn uses these values to push data to the Cognitive search service.

**Comment by en-coded** [comment]
Thank you for the suggestion. I have implemented it. Resolving.
