### ISSUE TITLE
How do I run prepdocs with an argument (specifically --removeall)

### ISSUE THREAD

**Issue by seef-leroux** [Azure-Samples/azure-search-openai-demo#596]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
I want to clear out my index. To do this I want to run prepdocs with --removeall. Please can you assist with basic instructions?

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
In scripts/prepdocs.sh, find the final line:

./scripts/.venv/bin/python ./scripts/prepdocs.py './data/*' --storageaccount "$AZURE_STORAGE_ACCOUNT" --container "$AZURE_STORAGE_CONTAINER" --searchservice "$AZURE_SEARCH_SERVICE" --openaiservice "$AZURE_OPENAI_SERVICE" --openaideployment "$AZURE_OPENAI_EMB_DEPLOYMENT" --index "$AZURE_SEARCH_INDEX" --formrecognizerservice "$AZURE_FORMRECOGNIZER_SERVICE" --tenantid "$AZURE_TENANT_ID" -v


Add --removeall to that line, before --storageaccount

Then run ./scripts/prepdocs.sh

If you are instead using prepdocs.ps1 due to being on a Windows machine, the same directions apply there.

Let me know if thats not clear.

**Comment by seef-leroux** [comment]
Thank you, your answer was clear! I have run it, but it seems to be stuck on a point:
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/142386050/d84338b2-857a-4df5-b2e1-1e2681c60131)

**Comment by seef-leroux** [comment]
Your answer was clear, thank you very much. It executed without error, but it seems to be stuck on loading the .enz file:
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/142386050/f1344fc4-65d3-475e-8eba-240327b5b013)

**Comment by seef-leroux** [comment]
Restarting the computer and running the script again worked.
