### ISSUE TITLE
while trying to deploy the app using azure devops pipeline,i am getting below error

### ISSUE THREAD

**Issue by balaram91** [Azure-Samples/azure-search-openai-demo#599]
{"code":"InvalidTemplateDeployment","message":"The template deployment failed with error: 'Authorization failed for template resource 'f24506f9-8e57-5059-898e-86700306d8b2' of type 'Microsoft.Authorization/roleAssignments'. The client '6705b63d-4d74-4fe9-b096-291f7f12907c' with object id '6705b63d-4d74-4fe9-b096-291f7f12907c' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/71d6e437-0bc6-40e9-b79f-6bcdbf924d00/resourceGroups/rg-aes-process-automation/providers/Microsoft.Authorization/roleAssignments/f24506f9-8e57-5059-898e-86700306d8b2'.'."}

**Comment by felixwcf** [comment]
You do not have permission to create new Azure resources. Seek your IT who manage Azure services.

**Comment by pamelafox** [comment]
FYI: We've clarified on the README that at the minimum, you need the RBAC role to run `azd up`, or the RBAC role scoped to an existing resource group: https://github.com/Azure-Samples/azure-search-openai-demo#azure-account-requirements

We're interested to hear if your employers are able to give you that level of access (especially resource group scoped) or if that is still high of a level of access. 

I also documented in another issue how to manually assign the roles in the Portal, but I assume that will only work if you have RBAC access for that RG:

https://github.com/Azure-Samples/azure-search-openai-demo/issues/634#issuecomment-1721699823

If you cannot be granted RBAC at the resource group level, then I think the only other approach is to use keys instead of managed identity. That should be possible with changes to the credentials in app.py. We generally discourage keys when possible, however, so we haven't yet enabled that in the repo.
