### ISSUE TITLE
Add model for /chat response 

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/azure-search-openai-demo#744]
Can the frontend have a model for the [/chat response](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/frontend/src/api/api.ts#L50)? That would make it quicker to understand what is returned.

**Comment by pamelafox** [comment]
Can you clarify what response you're looking for that isn't in 

https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/frontend/src/api/models.ts

?

**Comment by pamelafox** [comment]
We talked offline, and I think issue is that api.ts only returns back Response for /chat request. That's because it gets turned into an actual object in the chat code as parsing is more complex depending on streaming status. 

See https://github.com/Azure-Samples/azure-search-openai-demo/blob/a1170562395ad122d2be0e8e29d33cac7ff169c2/app/frontend/src/pages/chat/Chat.tsx#L128

I think this can be closed.
