### ISSUE TITLE
Inconsistent temperature

### ISSUE THREAD

**Issue by laszlohabon** [Azure-Samples/azure-search-openai-demo#943]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> semantic bug in chatreadretrieveread.py:

in line 134 temperature is set to 0 then in 231 if there is no override it is set to 0.7. this makes the messages after the first one inconsistent

### Any log messages given by the failure
>

### Expected/desired behavior
> temperature should remain 0 if no override.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
ChatReadRetrieveRead makes 2 calls to ChatGPT for two different purposes. The first call turns the user question into a search query. The second call actually answers the question. We use 0 for the first call as we don't desire creativity, but we use 0.7 for the second so that the answers are more creative. You may change 0.7 if you'd like less variability in the answers.
